# Generated by Django 4.2.15 on 2026-06-13 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_no', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('customer_name', models.CharField(max_length=50)),
                ('desired_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', '활성'), ('cancelled', '취소')], default='active', max_length=10)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order_date', 'order_no'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('매트리스', '매트리스'), ('토퍼', '토퍼'), ('프레임', '프레임'), ('베개', '베개')], max_length=20)),
                ('size', models.CharField(choices=[('SS', 'SS'), ('Q', 'Q'), ('K', 'K'), ('STD', 'STD')], max_length=10)),
                ('unit_price', models.IntegerField(help_text='단가 (표시용)')),
                ('initial_stock', models.IntegerField(help_text='시뮬레이션 시작일의 초기 재고')),
                ('safety_stock', models.IntegerField(help_text='안전재고')),
                ('reorder_point', models.IntegerField(help_text='재주문점: 가용재고가 이 값 이하이면 발주')),
                ('moq', models.IntegerField(help_text='생산 로트(최소 발주 단위)')),
                ('production_lead_time_days', models.IntegerField(help_text='생산 리드타임(일)')),
                ('delivery_lead_time_days', models.IntegerField(help_text='배송 리드타임(일)')),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='SimulationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='시뮬레이션 시작일')),
                ('end_date', models.DateField(help_text='시뮬레이션 종료일 (필요 시 자동 연장됨)')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFulfillment',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fulfillment', serialize=False, to='inventory.order')),
                ('stock_deducted_date', models.DateField(blank=True, help_text='재고가 실제로 차감된 날 (NULL이면 백오더 대기)', null=True)),
                ('shipped_date', models.DateField(blank=True, help_text='배송 출발일(출고일)', null=True)),
                ('expected_arrival_date', models.DateField(blank=True, help_text='고객 도착예정일 = 출고일 + 배송리드타임', null=True)),
                ('status', models.CharField(choices=[('pending', '대기(백오더)'), ('normal', '정상'), ('simple_delay', '단순 지연'), ('promise_kept', '약속 이행'), ('promise_broken', '약속 불이행')], default='pending', max_length=20)),
                ('delay_days', models.IntegerField(default=0)),
                ('root_cause', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(help_text='발주일')),
                ('quantity', models.IntegerField(help_text='발주수량 (MOQ 1회분)')),
                ('expected_arrival_date', models.DateField(help_text='입고예정일 = 발주일 + 생산리드타임')),
                ('status', models.CharField(choices=[('pending', '입고 예정'), ('received', '입고 완료')], default='pending', max_length=10)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('trigger_reason', models.TextField(help_text='발주 트리거 사유. 예: "가용재고 10 ≤ 재주문점 12"')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='inventory.product')),
            ],
            options={
                'ordering': ['expected_arrival_date', 'id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inventory.product'),
        ),
        migrations.CreateModel(
            name='DailyLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_stock', models.IntegerField(help_text='기초재고 (전일 기말재고)')),
                ('production_inbound', models.IntegerField(default=0, help_text='당일 생산입고(+)')),
                ('order_outbound', models.IntegerField(default=0, help_text='당일 주문출고(-), 재고 차감 기준')),
                ('closing_stock', models.IntegerField(help_text='기말재고')),
                ('available_stock', models.IntegerField(help_text='가용재고 = 기말재고 + 미입고발주합 - 백오더잔량 (음수 허용)')),
                ('order_quantity_today', models.IntegerField(default=0, help_text='당일 발생한 생산발주 수량 합')),
                ('backorder_balance', models.IntegerField(default=0, help_text='당일 마감 시점의 백오더(미출고 주문) 잔량')),
                ('structural_shortage_flag', models.BooleanField(default=False, help_text='가용재고가 음수이면 True (구조적 재고 부족)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_rows', to='inventory.product')),
            ],
            options={
                'ordering': ['product', 'date'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyledger',
            constraint=models.UniqueConstraint(fields=('product', 'date'), name='unique_ledger_per_day'),
        ),
    ]
